
import scipy as sp
import numpy as np
from scipy.special import expit
import random
poop='AYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFSNVTWFHNPVLPFNDGVYFASTEKSNIIRGWIFGTTLDSKTQSLLIVNNATNVVIKVCEFQFCNDPFLSEFRVYSSANNCTFEYVSQPFLKNLREFVFKNIDGYFKIYSKHTPPQGFSALEPLVDLPIGINITRFQTLLAAYYVGYLQPRTFLLKYNENGTITDAVDCALDPLSETKCTLKSFTVEKGIYQTSNFRVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSYNYLYRNLKPFERDISTEIYNCYFPLQSYGFQPTVGYQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVNFNFNGLTGTGVLTESNKKFLPFQQFGRDIADTTDAVRDPQTLEILDITPCSFGGVSVITPGTNTSNQVAVLYQDVNCTEVTGSNVFQTRAGCLIGAEHVNNSYECDIPIGAGICAVASQSIIAYTMSLGAENSVAYSNNSIAIPTNFTISVTTEILPVSMTKTSVDCTMYICGDSTECSNLLLQYGSFCTQLNRALTGIAVEQDKNTQEVFAQVKQIYKTPPIKDFGGFNFSQILPDPSKRSFIEDLLFNKVTLQKFNGLTVLPPLLTDEMIAQYTSALLAGTITSGWTFGAGAALQIPFAMQMAYRFNGIGVTQNVLYENQKLIANQFNSAIGKIQDSLSSTASALGKLQDVVNQNAQALNTLVKQLSSNFGAISSVLNDILSRLDPPEAEVQIDRLITGRLQSLQTYVTQQLIRAAEIRASANLAATKMSECVLGQSKRVDFCGKGYHLMSFPQSAPHGVVFLHVTYVPAQEKNFTTAPAICHDGKAHFPREGVFVSNGTHWFVTQRNFYEPQIITTDNTFVSGNCDVVIGIVNNTVYDPLQPELD'
s=random.sample(poop,len(poop))
p=''
for i in range(len(s)):
    p+=s[i]
print(p)
List = np.genfromtxt("Popular vote backend - Sheet1.tsv", delimiter="\t")
file=open('Trump Weed - Sheet1.tsv',"r")
i=0
TrainingSize=30
hiddenlayernodes=2
input=List[0:TrainingSize,(3,4,5,6)]
weights1= np.random.rand(input.shape[1],hiddenlayernodes)
weights2   = np.random.rand(hiddenlayernodes,1)
y=List[0:TrainingSize,-1]
output= np.zeros((y.shape))
layer1 = expit(np.dot(input, weights1))
output = expit(np.dot(layer1, weights2))
d_weights2 = np.dot((2*(y - output.T) * (output.T*(1-output.T))), layer1)
dC_da=np.dot(weights2, 2*(y - output.T) * ((output.T*(1-output.T))) )* (layer1.T*(1-layer1.T))
d_weights1 = np.dot(input.T, dC_da.T)

weights1 += d_weights1

weights2 += d_weights2.T
input=List[0:,(3,4,5,6)]
y=List[0:,-1]
output= np.zeros((1,51))
layer1 = expit(np.dot(input, weights1))
output = expit(np.dot(layer1, weights2))
print(y)
print(output.T)